# Generated by Django 2.2.4 on 2019-08-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperboy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperboy',
            name='earnings',
        ),
    ]
